//LOCAL STORAGE KEYS
export const STORAGE_KEY_ITEM_LIST = "STORAGE_KEY_ITEM_LIST"
export const STORAGE_KEY_FAVORITE_ID_LIST = "STORAGE_KEY_FAVORITE_ID_LIST"
export const STORAGE_KEY_BASKET_ID_LIST = "STORAGE_KEY_BASKET_ID_LIST"

//ROUTE PATHS
export const ROUTE_PATH_ITEM_LIST = "/"
export const ROUTE_PATH_BASKET = "/basket"